name: dbconnect
channels:
  - conda-forge
dependencies:
  - python=3.7.3
  - pip
  - pip:
      - databricks-connect==7.1.1
      - six
      - flask==0.12
      - flask_restful==0.3.5
      - gunicorn
